version: "3.9"

services:
    flask:
        build: .
        ports:
            - "5001:5001"
        volumes:
            - .:/app
        environment:
            - FLASK_APP=src/main.py
            - FLASK_ENV=development
            - FLASK_RUN_HOST=0.0.0.0
            - FLASK_RUN_PORT=5001
